### ISSUE TITLE
NSApp.activate(ignoringOtherApps: true) is deprecated.

### ISSUE THREAD

**Issue by ShikiSuen** [sindresorhus/Settings#102]
https://github.com/sindresorhus/Settings/blob/1e96f6f4df71da8a0e8cad089015985264fc0d95/Sources/Settings/SettingsWindowController.swift#L100
https://developer.apple.com/documentation/macos-release-notes/appkit-release-notes-for-macos-14
![image](https://github.com/sindresorhus/Settings/assets/3164826/1cc2080d-06af-4313-bd4e-344786b31e2d)

**Comment by DivineDominion** [comment]
Sounds like an easy change with if-#available checks, if needed.

Would you be able to add a PR and test with Xcode 15 beta?

**Comment by ShikiSuen** [comment]
@DivineDominion A PR is OK and I'm gonna do it.
I just don't know how to design a test for this.
We can deal with the new unit tests later.

**Comment by ShikiSuen** [comment]
@DivineDominion Here's the PR now. https://github.com/sindresorhus/Settings/pull/103
