### ISSUE TITLE
[Feature Request] Prefer to use LocalizedStringKey in Settings's SwiftUI interface

### ISSUE THREAD

**Issue by Kyle-Ye** [sindresorhus/Settings#116]
Add another overload init method using `LocalizedStringKey` for title's type in SwiftUI API.

https://github.com/sindresorhus/Settings/blob/b1f022abae4303fdc89f90af3b7d15d723b7886d/Sources/Settings/Section.swift#L91-L96

When a SwiftUI View need some string value which will be rendered on screen and need localization, it is recommended the client pass in a LocalizedStringKey by default instead of a String. (2 init with the same name and probably mark the String one @_disfavoredOverload if needed)

See other library's usage

- https://github.com/Kyle-Ye/AcknowKit/blob/f4b73e729fc51d53c2046ad89e3ac78560ea46f8/Sources/AcknowKit/Model/AcknowLibrary.swift#L21-L25

If the author agrees the idea, I'm glad to make such PR.

**Comment by sindresorhus** [comment]
Sure

**Comment by Kyle-Ye** [comment]
Under the hood, `Pane` just pass the title property to `PaneHostingController` and then used in `NSWindow` and `NSToolbarItem` which only accepts String.

https://github.com/sindresorhus/Settings/blob/b1f022abae4303fdc89f90af3b7d15d723b7886d/Sources/Settings/Pane.swift#L67-L74

But LocalizedStringKey only works in SwiftUI. (It needs to be resolved in `SwiftUI.EnvironmentValues` under the hood internally)

And once you get a LocalizedStringKey by StringLiteral, you can't get back the original string. So we can't do the following code as a fallback solution.

```
public init(
	identifier: PaneIdentifier,
	title: LocalizedStringKye,
	toolbarIcon: NSImage,
	contentView: () -> Content
) {
	self.identifier = identifier
	self.title = NSLocalizedString(title.xx, comment: "")
	self.toolbarIcon = toolbarIcon
	self.content = contentView()
}
```

So I'll just close the issue now until we have some SwiftUI View to consume the title property in the future.
