### ISSUE TITLE
SwiftUI unexpected switching animation

### ISSUE THREAD

**Issue by honghaoz** [sindresorhus/Settings#59]
I used SwiftUI to build preference panels. However, when switching tabs, the view jumps with a weird animation. I feel this is because the SwiftUI view hasn't loaded when switching.

This only happens for the first time switching.

See:
![CleanShot 2020-08-05 at 12 14 29](https://user-images.githubusercontent.com/3926785/89454343-6a8afc80-d715-11ea-8455-89592fcf4cb9.gif)

My current workaround is to disable the animation:
```swift
_ = PreferencesWindowController(
  preferencePanes: [...],
  style: .toolbarItems,
  animated: false, // <---
  hidesToolbarForSingleItem: true
)
```

**Comment by sindresorhus** [comment]
// @fredyshox

**Comment by hisaac** [comment]
Just want to echo that I'm also having this issue as of 2021-02-17. This is also the same as #60.

**Comment by hisaac** [comment]
User @gaozhanting has a workaround for this issue here: https://github.com/sindresorhus/Preferences/issues/60#issuecomment-886146196
