### ISSUE TITLE
Incorrect animation for first transition to preference pane with different width

### ISSUE THREAD

**Issue by JosephDuffy** [sindresorhus/Settings#60]
When animating to a preference pane that has not been loaded before and has a larger width than the current pane the view is not correctly laid out initially, which causes an odd animation. The animation is correct in subsequent switches.

The example below is the example app with the width = 450 constraint removed from the Advanced tab, and the app set to open to the Advanced tab.

![Screen Recording 2020-08-23 at 19 39 33 2020-08-23 19_49_52](https://user-images.githubusercontent.com/1325813/90986321-e9878e00-e579-11ea-9cb7-9b49d773ac0a.gif)

I'm trying to figure out the exact scenarios that causes this. Starting on Accounts does not cause this same animation to happen so I'm not sure how the size change and animations are linked.

**Comment by mohakapt** [comment]
I'm having exactly the same issue here. Only with me it's happening with different heights.

**Comment by mohakapt** [comment]
I was able to make it a little bit less annoying by adding a fade animation when moving between panes.

It doesn't completely fix the issue you can still notice the jump if you're looking for it, but this anmiation made the jump somewhat less obvious.

``` swift
  override func viewWillAppear() {
    super.viewWillAppear()
    self.view.subviews.first?.alphaValue = 0
    DispatchQueue.main.asyncAfter(deadline: .now() + .milliseconds(300)) {
      self.view.subviews.first?.animator().alphaValue = 1
    }
  }

  override func viewWillDisappear() {
    super.viewWillDisappear()
    self.view.subviews.first?.animator().alphaValue = 0
  }
```

**Comment by hisaac** [comment]
Just want to echo that I'm also having this issue as of 2021-02-17. This is also the same as #59.

**Comment by gaozhanting** [comment]
I think you can make a workaround:

```swift
func fixFirstTimeLanuchOddAnimationByImplicitlyShowIt() {
     preferencesWindowController.show(preferencePane: .general)
     preferencesWindowController.show(preferencePane: .advanced)
     preferencesWindowController.show(preferencePane: .accounts)
     preferencesWindowController.close()
}
```

then call it in `applicationDidFinishLaunching`

**Comment by hisaac** [comment]
@gaozhanting Nice, this works! Any idea why it works?

**Comment by gaozhanting** [comment]
Because the odd animation only happens the first time you open the tab when you integrate it with Swift UI view. With this way, it already done immediately after app lanuched, only that user can't see it again afterward.
