### ISSUE TITLE
Rename project to `Settings`

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/Settings#76]
Later this year.

- While I'm doing that, also rename `preferencePaneIdentifier` to `paneIdentifier` and `preferencePaneTitle` to `paneTitle`. And the `preferencePanes` parameter to `panes`.

**Comment by ShikiSuen** [comment]
Maybe SDSettings is better. General names like "Settings" and "Preferences" can cause serious confilcts with certain names occupied by Apple.

For example: InputMethodKit preference panel (shown in macOS System Preferences / Settings) requires that the target name of the pref pane has to be "Preferences". This causes building conflict with the "sindresorhus / Preferences" package.

**Comment by DivineDominion** [comment]
@sindresorhus Looks like there's not much left to do: I spotted that the `Sources/` subfolder would need to finally be changed, and applies some renames in #90 

Also needs to be changed the window's autosave name:

```swift
extension NSWindow.FrameAutosaveName {
	static let settings: NSWindow.FrameAutosaveName = "com.sindresorhus.Preferences.FrameAutosaveName"
}
```

And the localization strings.

**Comment by DivineDominion** [comment]
@ShikiSuen The prefixes usually aren't necessary anymore when you can disambiguate by using Swift module names. Wouldn't this also work for the `InputMethodKit` problem you described?

**Comment by ShikiSuen** [comment]
@DivineDominion Sorry, it doesn't work. It stops the project from being compiled.

**Comment by ShikiSuen** [comment]
@DivineDominion Nevertheless, I see that you are about to rebrand this project to `Settings`. I believe that this will mitigate this issue for the current version of the InputMethodKit. However, InputMethodKit is subject to further unknown changes.
